"""empty message

Revision ID: d159ec9bb680
Revises: 
Create Date: 2019-09-29 19:25:39.239446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd159ec9bb680'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('c_id', sa.String(length=32), nullable=True),
    sa.Column('c_name', sa.String(length=32), nullable=True),
    sa.Column('c_time', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leave',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('leave_id', sa.Integer(), nullable=True),
    sa.Column('leave_name', sa.String(length=32), nullable=True),
    sa.Column('leave_type', sa.String(length=32), nullable=True),
    sa.Column('leave_start_time', sa.String(length=32), nullable=True),
    sa.Column('leave_end_time', sa.String(length=32), nullable=True),
    sa.Column('leave_description', sa.Text(), nullable=True),
    sa.Column('leave_phone', sa.String(length=32), nullable=True),
    sa.Column('leave_status', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('picture',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('picture', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=32), nullable=True),
    sa.Column('user_email', sa.String(length=32), nullable=True),
    sa.Column('user_password', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('picture')
    op.drop_table('leave')
    op.drop_table('curriculum')
    # ### end Alembic commands ###
