"""empty message

Revision ID: 90e3a5097a42
Revises: f2b05440494a
Create Date: 2019-09-27 16:59:43.547043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90e3a5097a42'
down_revision = 'f2b05440494a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picture', sa.Column('name', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('picture', 'name')
    # ### end Alembic commands ###
